name: Build Docker Image

on: 
  workflow_dispatch:

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: docker login
        run: |
          docker login -u ankit247 -p ${{ secrets.GH_PACKAGE_PAT }} ghcr.io
      - name: docker build
        run: |
          docker buildx build ./ --push -t ghcr.io/ankit247/ubuntu_asic:latest \
          --cache-to type=registry,ref=ghcr.io/ankit247/ubuntu_asic-cache \
          --cache-from type=registry,ref=ghcr.io/ankit247/ubuntu_asic-cache
