name: Build Docker Image

on: 
  workflow_dispatch:

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: docker login
        run: |
          echo ${{ secrets.GH_PACKAGE_PAT }} | docker login ghcr.io -u ankit247 --password-stdin          
      - name: docker build
        run: |
          docker buildx build ./ --push -t ghcr.io/ankit247/ubuntu_asic:latest \
          --cache-to type=gha,ref=ghcr.io/ankit247/ubuntu_asic-cache \
          --cache-from type=gha,ref=ghcr.io/ankit247/ubuntu_asic-cache && \
          docker image ls
          
