name: Build Docker Image

on: 
  workflow_dispatch:

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: docker login
        run: |
          docker login -u ankit247 -p ${{ secrets.GH_PACKAGE_PAT }} ghcr.io
      - name: docker build
        run: |
          docker build ./ -t ghcr.io/ankit247/ubuntu_asic:latest
      - name: docker push
        run: |
          docker push ghcr.io/ankit247/ubuntu_asic:latest
      - name: run docker
        run: |
          docker run ubuntu_asic --name ubuntu_asic_c echo running docker
