name: Run Docker Container

on: 
  workflow_dispatch:

jobs:
  run-docker-container:
    name: run docker container
    runs-on: ubuntu-latest
    
    steps:
      - name: docker login
        run: |
          docker login -u ankit247 -p ${{ secrets.GH_PACKAGE_PAT }} ghcr.io
      - name: run docker
        run: |
          docker pull ghcr.io/ankit247/ubuntu_asic:latest
          docker run ghcr.io/ankit247/ubuntu_asic --name ubuntu_asic_c echo running docker
