name: Run Docker Container

on: 
  workflow_dispatch:

jobs:
  run-docker-container:
    name: run docker container
    runs-on: ubuntu-latest
    
    steps:
      - name: docker login
        run: |
          echo ${{ secrets.GH_PACKAGE_PAT }} | docker login ghcr.io -u ankit247 --password-stdin
      - name: run docker
        run: |
          docker pull ghcr.io/ankit247/ubuntu_asic:latest
          docker run --name ubuntu_asic_c ghcr.io/ankit247/ubuntu_asic  which sbt
